export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const FETCH_USER_GOALS = "FETCH_USER_GOALS";
export const ADD_USER_GOAL = "ADD_USER_GOAL";
export const UPDATE_USER_GOAL = "UPDATE_USER_GOAL";
export const DELETE_USER_GOAL = "DELETE_USER_GOAL";
export const FETCH_USER_CHALLENGES = "FETCH_USER_CHALLENGES";
